apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment-COLOR
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
        label: COLOR
    spec:
      containers:
      - image: node:9.11
        name: nodejs
        command: ["node", "/usr/src/app/index.js"]
        ports:
        - containerPort: 8080 
        volumeMounts:
        - name: app-volume
          mountPath: /usr/src/app     
      volumes:
        - name: app-volume
          configMap:
            name: nodejs-app
